version: '3'
services:
 front:
  container_name: front
  restart: always
  build:
   context: frontend
  ports:
   - '80:8080'
 back:
  container_name: back
  restart: always
  build:
   context: backend
  ports:
   - '5000:5000'